//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SundooqLanding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sources
    {
        public Sources()
        {
            this.Topics = new HashSet<Topics>();
        }
    
        public int Id { get; set; }
        public string SourceName { get; set; }
        public string LogoURL { get; set; }
        public string Tags { get; set; }
        public string URL { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> Status { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Topics> Topics { get; set; }
    }
}
