//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SundoqEmailSender
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int TopicId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> Impression { get; set; }
    
        public virtual Topics Topics { get; set; }
        public virtual Users Users { get; set; }
    }
}
